[project]
name = "people-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "filterpy>=1.4.5",
    "opencv-python>=4.10.0.84",
    "ultralytics>=8.3.18",
]
